Add Zephyr User-Space sample implementation
Sensirion/embedded-common pull request #52
Opened 2020-08-22 00:35 UTC by bwasim

Porting the SPS30 driver to Zephyr User-Space (https://github.com/zephyrproject-rtos/zephyr). Tested with nRF9160 and STM32L4.

2020-08-24 06:37 UTC, abrauchli requested changes
Hi @bwasim, many thanks for your contribution, it's great to see a Zephyr implementation! Additional kudos for specifying what hardware this was tested on.

I added a couple of comments. Mostly on style consistency with the rest of the repo, structurally it looks good. Could you have a look at those comments and resubmit, then we should be able to merge this.

Kind regards

2020-08-24 06:37 UTC, abrauchli commented on hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
> +#include <string.h>
is `<string.h>` needed?

2020-08-24 06:37 UTC, abrauchli commented on hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
> +	/* Get device from the provided bus index (only support 0-9). */
Would be good to add a guard on this (`0 <= bus_inx <= 9`), otherwise we're shifting the validation burden to `device_get_binding()`. For simplicity I'd return `STATUS_FAIL` in that case, but we're aware that the error codes are currently lacking differentiation...

2020-08-24 06:37 UTC, abrauchli commented on hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
> +	bus_name[4] = bus_idx +'0';
space missing after `+` operator, `clang-format` should take care of that, too.

```suggestion
	bus_name[4] = bus_idx + '0';
```

2020-08-24 06:37 UTC, abrauchli commented on hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
> +		status = STATUS_OK;
I don't think we have a strict policy on control flow, but we tend to prefer the straight flow to be the "success"/no-error flow, while errors branch out. As such I'd flip the check.

Also, status is always constant wrt. the branch so we can drop the `status` variable.

```
    if (sps30_i2c_dev == NULL)
        return STATUS_FAIL;

    return STATUS_OK;
```

2020-08-24 06:37 UTC, abrauchli commented on hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
> +						   uint16_t count)
Could you change the whole file's indentation to using spaces to match the repo's style? (You should be able to have the file reformatted with `clang-format -i $(find . -name "*.[ch]")`

2020-08-24 06:37 UTC, abrauchli commented on hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
> +static struct device *sps30_i2c_dev;
The repo's style is to keep the pointer with the type. See comment on `clang-format` below...

2020-08-24 06:39 UTC, abrauchli commented
..just an additional comment on the PR naming: since this is the `embedded-common` repo, all `embedded-*` drivers from Sensirion will be able to benefit from the Zephyr implementation, not just the SPS30. As such, I're rename the PR to something like `Add Zephyr User-Space sample implementation`

2020-09-10 14:05 UTC, bwasim commented
Thanks for pointing out the various improvements - I've integrated the changes and updated the pull request.

2020-09-11 13:22 UTC, abrauchli requested changes
Again, many thanks for your changes. I spotted two more things to fix before we can merge: the implementation is not specific to the SPS30, so I'm suggesting a more generic name and the second one is a matter of the control-flow style I'd like to consider rearranging.

2020-09-11 13:22 UTC, abrauchli commented on hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
> +static struct device* sps30_i2c_dev;
I suggest using a more abstract name, since this affects all devices using this implementation

```suggestion
/* I2C device. */
static struct device* i2c_dev;
```

2020-09-11 13:22 UTC, abrauchli commented on hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
> +    return STATUS_FAIL;
I suggest reorganizing the control-flow to always branch out on error, that should make it easier to read what the expected case is and causes less indentation.

```suggestion
    if (bus_idx > 9) {
        /* Invalid bus index */
        return STATUS_FAIL;
    }

    bus_name[4] = bus_idx + '0';
    i2c_dev = device_get_binding(bus_name);
    if (i2c_dev == NULL) {
        /* No valid device found */
        return STATUS_FAIL;
    }

    return STATUS_OK;
```

2020-09-11 13:22 UTC, abrauchli commented on hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
> +    sps30_i2c_dev = NULL;
```suggestion
    i2c_dev = NULL;
```

2020-09-11 13:22 UTC, abrauchli commented on hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
> +    return i2c_read(sps30_i2c_dev, data, count, address);
```suggestion
    return i2c_read(i2c_dev, data, count, address);
```

2020-09-11 13:22 UTC, abrauchli commented on hw_i2c/sample-implementations/zephyr_user_space/sensirion_hw_i2c_implementation.c
> +    return i2c_write(sps30_i2c_dev, data, count, address);
```suggestion
    return i2c_write(i2c_dev, data, count, address);
```

2020-09-11 13:53 UTC, abrauchli approved these changes
Many thanks

2020-09-11 13:58 UTC, merged