Rework readme
Sensirion/embedded-common pull request #86
Opened 2021-01-28 15:05 UTC by Zifzaf

2021-01-28 15:34 UTC, abrauchli requested changes

2021-01-28 15:34 UTC, abrauchli commented on i2c/README.md
> +`sample-implementations/linux_user_space/`:
```suggestion
This file contains the implementation of the sensor communication, which
depends on your hardware platform. We provide function stubs for your
hardware's own implementation.
Sample implementations are available for some platforms:
[`sample-implementations`](sample-implementations). For Linux
based platforms like Raspberry Pi you can just replace the unimplemented HAL
template with the implementation in
`sample-implementations/linux_user_space/`:
```

2021-01-28 15:34 UTC, abrauchli commented on i2c/README.md
> +already correctly setup for you.
```suggestion
Skip this part for Linux based platforms since everything is already setup for this case.
```

2021-01-28 15:34 UTC, abrauchli commented on i2c/README.md
> +The features we use out of those libraries are standard integer sizes from
```suggestion
The features we use from those libraries are type definitions for integer sizes from
```

2021-01-28 15:34 UTC, abrauchli commented on i2c/README.md
> +Take the `.c` and `.h` files directly in this folder pass them to your favorite
```suggestion
Pass the source `.c` and header `.h` files in this folder into your
```

2021-01-28 15:34 UTC, abrauchli commented on i2c/README.md
> +3. Run `make` (this compiles all the code here to one binary).
```suggestion
3. Run `make` (this compiles the example code into one executable binary).
```

2021-01-28 15:34 UTC, abrauchli commented on i2c/README.md
> +   binary).
```suggestion
4. Run the compiled executable with `./[SENSORNAME]_i2c_example_usage`
```

2021-01-28 15:34 UTC, abrauchli commented on i2c/README.md
> +In these files you can find the implementation of the hardware abstraction
```suggestion
These files contain the implementation of the hardware abstraction
```

2021-01-28 15:34 UTC, abrauchli commented on shdlc/README.md
> +This file contains the implementation of the sensor communication (how to send
suggestions above also apply to this file

2021-01-29 07:20 UTC, psachs approved these changes

2021-01-29 07:57 UTC, merged