Add example SAMDR i2c implementation
Sensirion/embedded-common pull request #96
Opened 2021-11-15 17:45 UTC by kelroy1990

Implementation of the I2C on the SAMDR architecture with the ASF framework from ATMEL.

Regards, Carlos.

2021-11-19 10:17 UTC, rnestler requested changes
Hi @kelroy1990

Thanks for the contribution! A few notes:
  * CI didn't seem to trigger since CircleCI seemed to be configured incorrectly. I changed it, so hopefully it will trigger next time you push
  * The code isn't formatted according to our style. Please use clang-format to fix it. (You may also use `make style-check`, which calls clang-format)
 * Please name the file sensirion_i2c_hal.c for consistency
  * Should this replace the `Atmel_SAMD2_series`? or is it really an additional implementation?

2021-11-19 10:17 UTC, rnestler commented on i2c/sample-implementations/Atmel_SAMDR_series/sensirion_i2c_ASF.c
> + * Copyright (c) 2018, Sensirion AG
```suggestion
 * Copyright (c) 2021, Sensirion AG
```

2021-11-19 10:17 UTC, rnestler commented on i2c/sample-implementations/Atmel_SAMDR_series/sensirion_i2c_ASF.c
> +				    break;
```suggestion
```

A `break` after a return doesn't make sense.

2021-11-19 10:19 UTC, rnestler commented on i2c/sample-implementations/Atmel_SAMDR_series/sensirion_i2c_ASF.c
> +*   #define TIMEOUT 1000
Can you add
```
#ifndef CONF_I2C_MASTER_MODULE
#define CONF_I2C_MASTER_MODULE SERCOM3
#endif
```
for all the defines? That way it compiles by default, but a user can still override the defines.

2021-12-25 15:22 UTC, kelroy1990 commented
@rnestler all changes done

Regards, Carlos.

2023-12-15 09:47 UTC, psachs approved these changes

2023-12-15 09:50 UTC, rnestler approved these changes
I approve as well :slightly_smiling_face:

2023-12-15 10:02 UTC, merged